site_name: Rares Algo
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js